// <auto-generated />
using EscolaDeIdiomas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaDeIdiomas.Migrations
{
    [DbContext(typeof(ContextoDB))]
    partial class ContextoDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscolaDeIdiomas.Models.AlunoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Aluno", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CPF = "10032136692",
                            Email = "arthur1@gmail.com",
                            Nome = "Arthur1"
                        },
                        new
                        {
                            Id = 2,
                            CPF = "20032136692",
                            Email = "arthur2@gmail.com",
                            Nome = "Arthur2"
                        },
                        new
                        {
                            Id = 3,
                            CPF = "30032136692",
                            Email = "arthur3@gmail.com",
                            Nome = "Arthur3"
                        },
                        new
                        {
                            Id = 4,
                            CPF = "40032136692",
                            Email = "arthur4@gmail.com",
                            Nome = "Arthur4"
                        },
                        new
                        {
                            Id = 5,
                            CPF = "50032136692",
                            Email = "arthur5@gmail.com",
                            Nome = "Arthur5"
                        },
                        new
                        {
                            Id = 6,
                            CPF = "60032136692",
                            Email = "arthur6@gmail.com",
                            Nome = "Arthur6"
                        },
                        new
                        {
                            Id = 7,
                            CPF = "70032136692",
                            Email = "arthur7@gmail.com",
                            Nome = "Arthur7"
                        });
                });

            modelBuilder.Entity("EscolaDeIdiomas.Models.TurmaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Turma", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "Eng01",
                            Nivel = "Iniciante"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "Eng02",
                            Nivel = "Intermediario"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "Eng03",
                            Nivel = "Avançado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
